services:
  - type: web
    name: click2lead-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: FLASK_ENV
        value: production
      - key: GRPC_PYTHON_BUILD_SYSTEM_OPENSSL
        value: 1
      - key: GRPC_PYTHON_BUILD_SYSTEM_ZLIB
        value: 1
      - key: GRPC_BUILD_WITH_BORING_SSL_ASM
        value: 0
      - key: GRPC_PYTHON_BUILD_WITH_CYTHON
        value: 0
    healthCheckPath: /api/status
    autoDeploy: true 