services:
  - type: web
    name: click2lead-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://user:password@host:port/database
    healthCheckPath: /api/status
    autoDeploy: true 